

export const LOCAL_HOST="https://prod.swiftbel.com";
export const LOCAL_HOST1="https://prod.swiftbel.com";

export const ServiceEnum={
    verifyEmail:'user/email',
    register:"user/register",
    completeProfile:'user/completeProfile',
    userDetails:"user/userDetails",
    customerDetails:'user/getUserDetails',
    updatecustomerDetails:'user/updateDetails',
    resendVerification:"user/resendVerification",
    setPassword:'user/setPassword',
    loginUser:'user/login',
    sendCode:'twilio/sendCode',
    verifyCode:'twilio/verify',
    serviceProvider:'serviceProvider/createAccount',
    googleSignup:'user/saveNewGoogleUser',
    googleLogin : 'user/login',
    appleSignup:'user/saveNewAppleUser',
    getPost:'serviceProvider/getPost',
    addNewPost:'serviceProvider/uploadPost',
    getBannerDetaiils:'serviceProvider/getImageBanner',
    uploadBannerImage:'serviceProvider/uploadImageBanner',
    twilioToken:'twilio/createToken',
    editProfile:'serviceProvider/editProfile',
    getServices:'serviceProvider/homePage',
    search:'search/filterSp',
    moving:'customer/Moving/v2/enterDetails',
    newmoving:'customer/Moving/v3/enterDetails',
    electricians:'customer/electrician/v1/enterDetails',
    Plumbers:'customer/plumbing/v1/enterDetails',
    hvac:'customer/hvacService/enterDetails',
    tilengrout:'customer/tileGroutCleaning/enterDetails',
    furnitureassemblydetails:'customer/furniture/enterDetails',
    handyman:'customer/handyMan/enterDetails',
    movingServices: 'movingService/enterPrice',
    housecleaning:'customer/houseCleaning/enterDetails',
    guttercleaning:'customer/gutterCleaning/enterDetails',
    pressurewashing:'customer/pressureWashing/v1/enterDetails',
    carpetcleaning:'customer/carpetCleaning/v1/enterDetails',
    rugcleaning:'customer/rugCleaning/enterDetails',
    hvacServices: 'hvacService/enterPrice',
    electricianServices: 'electricianService/enterPrice',
    plumberServices: 'PlumbingService/enterPrice',
    houseCleaningServices: 'houseCleaning/enterPrice',
    gethousecleaningServices:'houseCleaning/getPrice',
    windowCleaningServices: 'windowCleaningService/enterPrice',
    carpetCleaningServices: 'carpetCleaning/enterPrice',
    pressureWashingServices: 'pressureWash/enterPrice',
    gutterCleaningServices: 'gutterCleaning/enterPrice',
    handymanServices:'handyMan/enterPrice',
    furnitureAssembly:'furniture/enterPrice',
    tileandgroutService:'tileGroutCleaning/enterPrice',
    windowcleaning:'customer/windowCleaning/enterDetails',
    roofcleaning:'customer/roofCleaning/enterDetails',
    searchservice:'search/filterSp',
    confirmotp:'user/confirmOtp',
    confirmSignupotp:'user/matchOtp',
    inviteWorker:'serviceProvider/sendInviteLinkToWokers',
    workerList:'serviceProvider/workerList',
    stripePaymentIntent:'payment/paymentIntent',
    newCreateProfile:'serviceProvider/v1/createProfile',
    newPasswordSet:'serviceProvider/v1/setPassword',
    newSetServices:'serviceProvider/v1/addServiceOffered',
    getMovingServices:'movingService/getPrice',
    getElectricianServices:'electricianService/getPrice',
    getPressureWahing:'pressureWash/getPrice',
    getPlumbers:'PlumbingService/getPrice',
    adminLogin:'serviceProvider/v1/adminSpLogin',
    adminSignup:'serviceProvider/v1/adminSetupSpProfile',
    deletPost:'serviceProvider/deletePost',
    upcomingjobs:'serviceProvider/getUpcomingJobs',
    getNotificationData:'serviceProvider/getAllJobs',
    acceptJob:'serviceProvider/acceptJob',
    assignedJob:'serviceProvider/assignJob',
    manageJob:'serviceProvider/manageJobs',
    paymentBooking:'booking/new',
    getBookings:'booking/getAllBooking',
    addfavourite:'user/addFavouriteSp',
    savedjobs:'user/savedJob',
    Revenue:'search/totalRevenue',
    Businessverify:'payment/sp/details',
    ongoingJobs:'serviceProvider/getOnGoingJobs',
    useraccountdetails:'user/getUser',
    sendRequest:'user/admin/requestCall',
    adminSendEmail:'user/admin/sendEmail',
    getAdminDetails:'serviceProvider/v2/getDetails',
    savePatent:'booking/savePatent',
    advancePaymentIntent:'payment/advancePaymentIntent',
    resetPassword:'user/resetPassword',
    insurenceVaerification:'serviceProvider/insurance',
    verifcationMail:'user/generateOtp',
    matchOtp:'user/matchOtp',
    bannerPhotos:'user/mainPage/photo',
    cityPhotos:'user/landingPage/photo',
    citydetails:'user/cityDetails'

}

export const urlFor =(services)=>{
    if(services==="serviceProvider/v1/createProfile")
    {
            return `${LOCAL_HOST1}/${services}`
    }
    else if(services){
        return `${LOCAL_HOST}/${services}`
    }
    return undefined;
}